### PR TITLE
Adding in Mobile Web App.  WIP

### PR DESCRIPTION
**Pull request by lholmquist**
@bleathem so here is the WIP mobile web app.

atm you should be able to run `node server/server.js`  and then go to `localhost:PORT/mobile-app`

the drawings are not currently being sent to the server, but are stored in local storage.(hence the WIP in the title)

Just wanted to give an update

note:  if you see an issue, i'm probably already aware of it  :)

### CODE REVIEW

**Comment by lholmquist** [comment]
@bleathem so i think the best way to send the image data is probably as a base64 dataurl, that i can easily get from the drawing canvas.

I think you will need to update the endpoint to do something with it. it should be fairly easy to write to a file with this dataurl

**Comment by bleathem** [comment]
If we POST the image as a multipart form, we can user [multiparty](https://github.com/andrewrk/node-multiparty/) to handle it as a stream on the server.

To submit the image as a multipart POST, I believe we can use [canvas.toBlob](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob) and [FormData](https://developer.mozilla.org/en/docs/Web/API/FormData) to POST the image.

```
var multipart = new FormData();
multipart.append("canvasImage", canvas.toBlob());
```

or something like that.

**Comment by lholmquist** [comment]
Got the images creating correctly locally,  Things are stored on local storage after a succesful send to the server

**Comment by bleathem** [comment]
I had trouble running this locally using the Chrome "Enable touch screen" functionality.  Otherwise looks good!

Still outstaning work as I see it is:
- [ ] move `mobile-app` code into `static/mobile`
- [ ] remove bower dependency (I had to run `bower install` from within the mobile-app folder)
- [ ] enable the sketch to work with a desktop client (click events)

**Comment by bleathem** [comment]
Additionally the stream conversion of the multi-part POST needs to be moved a bit further up the stream-handling chain.  It should feed the forked stream handling here:

https://github.com/bleathem/keynote2015-hexboard/blob/3ddf13b57fb63967cde59d14eb025b22f0c2d1dd/server/api/sketch_controller.js#L141

If you prefer I can make this change post-merge.

**Comment by lholmquist** [comment]
i'll leave the modifying of the server to you once done.  i'll take care of those other 3 issues this morning

**Comment by lholmquist** [comment]
@bleathem i think that takes care of those 3 checkboxes

**Comment by bleathem** [comment]
Great, thanks @lholmquist.  I noticed a few usage issues as I was running it locally; I'll track those via new issues.

Merged. thanks!

**Pull request merged**
